springboot:
  jwt:
    access-secret: Pen1sie2vePersonalProject1Kim2suk0Kyung3lOvEs4yOUAll0977l
    refresh-secret: dOYou1wAnTtOReFreShYoUR0ToKeN312Kim2suk0Kyung3lOvEs4yOUAll0987
    header-scheme-name: authorization
    token-type: Bearer
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: smk93021@gmail.com
    password: pdnzwfnlsxajpwza
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 300000
      auth-code-prefix: PenSieveAutHCd4MailVerificatiOn
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/databasetest
    username: postgres
    password: green502
  servlet:
    multipart:
      max-file-size: 10MB
  #  neo4j:
  #    authentication:
  #      username: neo4j
  #      password: MlUm8DaSVbvcwFk3UYBz1YOBYS7tglSXHgP07WAvXlQ
  #      uri: bolt://neo4j+s://0630ee8d.databases.neo4j.io:7687
  data:
    redis:
      host: 192.168.0.117
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: 8085
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true



springdoc:
  default-consumes-media-type: application/json;charset=UTF-8

#파일업로드 경로
file:
  dir: D:/
  imgPath: http://192.168.0.117:8085/pensieve/data
