springboot:
  jwt:
    access-secret: Pen1sie2vePersonalProject1Kim2suk0Kyung3lOvEs4yOUAll0987
    refresh-secret: dOYou1wAnTtOReFreShYoUR0ToKeN312
    header-scheme-name: Authorization
    token-type: Bearer
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/databasetest
    username: postgres
    password: green502
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# swagger
springdoc:
  swagger-ui:
    path: /swagger.html