springboot:
  jwt:
    access-secret: Pen1sie2vePersonalProject1Kim2suk0Kyung3lOvEs4yOUAll0977l
    refresh-secret: dOYou1wAnTtOReFreShYoUR0ToKeN312Kim2suk0Kyung3lOvEs4yOUAll0987
    header-scheme-name: authorization
    token-type: Bearer
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/databasetest
    username: postgres
    password: green502
#  neo4j:
#    authentication:
#      username: neo4j
#      password: MlUm8DaSVbvcwFk3UYBz1YOBYS7tglSXHgP07WAvXlQ
#      uri: bolt://neo4j+s://0630ee8d.databases.neo4j.io:7687
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8085
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

#    operationsSorter: method
#    disable-swagger-default-url: true
#    display-request-duration: true

#  show-actuator: true
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  paths-to-match: /**
# swagger
#springdoc:
#  swagger-ui:
#    path: /
#    configUrl: /swagger-config.json
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /api-docs/json
#    groups:
#      enabled: true
#  cache:
#    disabled: true
#  packages-to-scan: *
##  com.example.pensieve


